### ISSUE TITLE
Bug in version 1.1.6 when advanced is not specified

### ISSUE THREAD

**Issue by ThumNet** [phelje/updateClickOnce#5]
Hi phelje, 

After the update to version 1.1.6 we are experiencing problems with this lovely Azure Pipeline Extension

Our pipeline throws the following error

```
##[error]The advanced config is not propperly formated! 
```

The `yml` syntax we are using for the task is:

```
  - task: IF-UpdateClickOnce@1
    displayName: Sign Manifest files
    inputs:
      ApplicationName: '${{parameters.productName}}'
      Publisher: 'OurCompany'
      Certificate: '$(cert.secureFilePath)'
      CertificatePassword: '<somepassword>'
      ProviderUrl: '${{parameters.url}}'
      ApplicationFolder: '$(Build.ArtifactStagingDirectory)\client'
      Version: $(Build.BuildNumber)
```

So as you can see we don't specify the `Advanced` input. This was working before!

Should we now set it to false or nothing or how do we fix our pipeline?

Thank you in advance

**Comment by ThumNet** [comment]
Adding the Advanced input as empty string resolved the issue.

```yml
- task: IF-UpdateClickOnce@1
    displayName: Sign Manifest files
    inputs:
      ApplicationName: '${{parameters.productName}}'
      Publisher: 'OurCompany'
      Certificate: '$(cert.secureFilePath)'
      CertificatePassword: '<somepassword>'
      ProviderUrl: '${{parameters.url}}'
      ApplicationFolder: '$(Build.ArtifactStagingDirectory)\client'
      Version: $(Build.BuildNumber)
      Advanded: '' # <---- this is needed to fix the issue
```
Maybe the check [here](https://github.com/phelje/updateClickOnce/blob/fb0de28bb451171fdf746d44af13267044375cf4/updateClickOnce/HelperFunctions.ps1#L144) could be improved?

**Comment by phelje** [comment]
Sorry for the trouble, seems like the switch to newer PowerShell lead to some issues.
Have released a new version 1.1.7 can you try it, and get back to me with the actual error message, i don't have this task set up in YAML pipeline seems like its behaving differently.

**Comment by ThumNet** [comment]
Nope, 1.1.7 doesn't fix the issue :( 
![image](https://user-images.githubusercontent.com/692308/111969281-59eb9300-8afa-11eb-9c7c-7836d54a9888.png)

The workaround still works though!

**Comment by phelje** [comment]
So, finally made a YAML pipeline to test it in.
When you don't specify the Advanced section it gets the default value, and when replacing commented lines the newline character was not replaced leading to error.
Latest version should fix it.

**Comment by ThumNet** [comment]
Sorry, but still not working

2021-03-24T08:01:36.6379513Z Advanced config enabled
2021-03-24T08:01:36.9775594Z ##[error]The advanced config is not propperly formated!

**Comment by phelje** [comment]
Can you enable system diagnostics,
![image](https://user-images.githubusercontent.com/8565356/112301504-4e36d280-8c9a-11eb-8507-51b5e18a8d7b.png)
and then see if you have the same data in INPUT_ADVANCED:
![image](https://user-images.githubusercontent.com/8565356/112301836-a372e400-8c9a-11eb-929a-3f0375776982.png)

**Comment by phelje** [comment]
My task looks like this:
- task: IF-UpdateClickOnce@1
  displayName: Sign Manifest files
  inputs:
    ApplicationName: 'MyApp'
    Publisher: 'OurCompany'
    Certificate: '$(caCertificate.secureFilePath)'
    CertificatePassword: $(passw)
    ProviderUrl: 'http://someurl/myapp'
    ApplicationFolder: '$(System.ArtifactsDirectory)/drop'
    Version: 1.23.4.5

**Comment by phelje** [comment]
My task looks like this:
```yaml
- task: IF-UpdateClickOnce@1
  displayName: Sign Manifest files
  inputs:
    ApplicationName: 'Appname'
    Publisher: 'OurCompany'
    Certificate: '$(caCertificate.secureFilePath)'
    CertificatePassword: $(passw)
    ProviderUrl: 'http://someurl/appname'
    ApplicationFolder: '$(System.ArtifactsDirectory)/drop'
    Version: 1.23.34.1
```

**Comment by phelje** [comment]
@ThumNet had time to test yet?

**Comment by ThumNet** [comment]
Yes, just got in another test, and I can confirm version 1.1.8 works without the Advanced setting configured!

**Comment by ThumNet** [comment]
Thank you for fixing this :)

**Comment by phelje** [comment]
Great to hear, sorry for causing trouble.
